# Generated by Django 5.2.3 on 2025-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersregistration',
            name='account_type',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor')], default='user', max_length=20),
        ),
    ]
