# Generated by Django 5.2.3 on 2025-07-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_alter_usersregistration_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersregistration',
            options={'verbose_name': 'User Registration', 'verbose_name_plural': 'Users Registrations'},
        ),
        migrations.AlterField(
            model_name='usersregistration',
            name='account_type',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor')], default='user', max_length=10, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='usersregistration',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, verbose_name='Agreed to Terms and Conditions'),
        ),
    ]
